FROM node:24.12.0-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci 

FROM node:24.12.0-alpine
WORKDIR /app


RUN chown -R node:node /app
USER node

COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/package*.json ./

COPY --chown=node:node . .

EXPOSE 3000
CMD ["node", "server.js"]