version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rag_engine
    volumes:
      - ./data_storage:/app/data_storage
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: rag_ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: rag_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend