version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rag_engine
    ports:
      - "8080:8080"
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: rag_ui
    ports:
      - "3000:3000"
    depends_on:
      - backend